name: Telco Churn ML Pipeline Vasyl Teraz Module 6

on:
    push:
        branches:
            - develop
            - 'module-**'
env:
    PYTHON_VERSION: "3.11"

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
              name: Checkout
            - name: "Setup Python ${{ env.PYTHON_VERSION }} env"
              uses: actions/setup-python@v5
            - name: Show version
              run: python -c "import sys; print(sys.version)"
